# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4bb098d19aea07f7ddbe8d0aedd0c0e37070b428a3f2a718470ae51e3be0af9a233b1705202fc98b506d2d1511f4b43aa7cafeb47590677a332d2a2de0dc4b10

test:
  secret_key_base: f630bf49c84e5dadbfafcb2744e6ab64e44af949dcbc41c930a96109d75972b9d4c074d448e1b5d96651b8d27f4474eb76de53bf334bf47e4e5e11380b70c1ec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
